### ISSUE TITLE
Vercel Deployment failing at the moment

### ISSUE THREAD

**Issue by Antonio-Bennett** [Antonio-Bennett/personal-website#4]
Vercel Deployments currently fail due to a bug potentially introduced [here](https://github.com/sveltejs/kit/pull/4192)
Bug is already reported [here](https://github.com/sveltejs/kit/issues/4224)
Due to this, #3 cannot be merged at the moment and deployed to production

**Comment by dev-justin** [comment]
Having the same issue, following this thread.

**Comment by Antonio-Bennett** [comment]
This issue can now be closed as adapter vercel has been updated and fixed
